---
# Apply latest Ruby style guide and newly introduced cops
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - '_snippets/**/*'
  Include:
  - 'Gemfile'
  - 'Rakefile'
  - '**/*.rb'

# ignore block length in test code only
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'rakefile.rb'
    - 'app/controllers/app.rb'
    - 'app/application/controllers/**/*.rb'
    - 'config/environment.rb'
    - 'db/migrations/002_episodes_create.rb'

# ignore method length in rebuilding entity only
Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'app/models/repositories/episodes.rb'

# ignore class length in controllers/app.rb
Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'app/application/controllers/app.rb'

# ignore Block Nesting in controllers/app.rb
Metrics/BlockNesting:
  Enabled: true
  Exclude:
    - 'app/application/controllers/app.rb'

# ignore Duplicate Branch in controllers/app.rb
Lint/DuplicateBranch:
  Enabled: true
  Exclude:
    - 'app/application/controllers/app.rb'

# See: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/MultilineMethodCallIndentation
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/HashSyntax:
  Enabled: true
  Exclude:
    - 'Rakefile'

Style/RedundantAssignment:
  Enabled: true
  Exclude:
    - 'app/domain/audio_datas/entities/audio_data.rb'

Style/OpenStructUse:
  Enabled: true
  Exclude:
    - 'app/application/controllers/app.rb'
    - 'app/application/services/view_podcast_info.rb'
    - 'app/application/services/add_podcast_info.rb'
    - 'app/application/services/list_podcast_infos.rb'
    - 'app/application/representers/openstruct_with_links.rb'
    - 'app/application/representers/episodes_view.rb'
    - 'app/application/representers/shows_view.rb'