---
development:
  # Infrastructure
  DB_FILENAME: db/local/dev.db
  spotify_Client_ID: provision_spotify_api_ID
  spotify_Client_secret: provision_spotify_api_secret
  # Application
  API_HOST: http://localhost:9292
  APP_HOST: http://localhost:9292
test:
  # Infrastructure
  DB_FILENAME: db/local/test.db
  spotify_Client_ID: provision_spotify_api_ID
  spotify_Client_secret: provision_spotify_api_secret
  # Application
  API_HOST: http://localhost:9292
  APP_HOST: http://localhost:9292
production:
  spotify_Client_ID: provision_spotify_api_ID
  spotify_Client_secret: provision_spotify_api_secret

